### ISSUE TITLE
BCP178 violation (x- prefix on parameters)

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/ratelimit-headers#103]
> To avoid clashes, implementers SHOULD prefix unregistered parameters with an `x-<vendor>` identifier, e.g. `x-acme-policy`, `x-acme-burst`.

See [BCP178](https://www.rfc-editor.org/rfc/rfc6648.html).

**Comment by ioggstream** [comment]
iirc there was a discussion on `x-` stuff. In general I'm ok with just `acme-` @unleashed do you see any issue with that?

**Comment by unleashed** [comment]
No issue, I was aware of the BCP and I think this case fits the first provision for segregating the name spaces in the Appendix B, so any one of the proposed solutions there, including yours, is fine with me.
