### ISSUE TITLE
Convey the quota-unit measurement unit (requests, bytes, ...) 

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/ratelimit-headers#128]
## Discussion

1. Should we standardize a way to convey the measurement unit (requests, bytes, ...) used by the quota-units ?
2. How ?

Forked discussion from #127 

## Notes

- currently we define the concept of quota-unit that is an integer related to the numer of requests that a service is willing to accept in a given time-window.
- the specification does not require that the quota-unit reflect the actual number of requests or something else. If it does not convey the number of requests (e.g. it is related to throughput) this should be conveyed out-of-band
- to standardize a measurement unit of quota, we should identify an interoperable solution

**Comment by darrelmiller** [comment]
New draft explicitly supports quota units https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers
