### ISSUE TITLE
A grammatical error

### ISSUE THREAD

**Issue by ant-222** [ietf-wg-httpapi/ratelimit-headers#129]
Hello.
The sentence:
> This specification does not cover whether non Successful responses count on quota usage, nor it mandates any correlation between the RateLimit values and the returned status code.

instead of _nor it mandates_, should have _nor does it mandate_.

**Comment by darrelmiller** [comment]
Fixed in latest draft https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers
