### ISSUE TITLE
mention of unregistered status code 430

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/ratelimit-headers#2]
<https://www.ietf.org/archive/id/draft-ietf-httpapi-ratelimit-headers-00.html#section-1.1-3>:

"When quota is exceeded, servers usually do not serve the request replying instead with a 4xx HTTP status code (eg. 429 or 403) or adopt more aggressive policies like dropping connections."

**Comment by ioggstream** [comment]
@reschke we are referencing `403 Forbidden`. Should we reference it somewhere?

**Comment by reschke** [comment]
Ah. Sorry for the noise.
