### ISSUE TITLE
Current ratelimit headers landscape

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/ratelimit-headers#25]
#### Compliant implementations: Zalando, IBM, 3scale, Kong, Dutch government, pipedrive, Envoy

Explicit support via `RateLimit-*` or `X-RateLimit-*` from:

 - [x] [Red Hat 3scale](https://issues.redhat.com/browse/THREESCALE-3795) 
 - [x] [Kong](https://github.com/Kong/kong/pull/5335)
 - [x] [Envoy proxy](https://github.com/envoyproxy/envoy/pull/12410)
 - [x] [Armeria Java API framework](https://github.com/line/armeria/blob/master/bucket4j/src/main/java/com/linecorp/armeria/common/throttling/ThrottlingHeaders.java#L24)
  - [x] [express-rate-limit](https://github.com/nfriedly/express-rate-limit/issues/168)
  - [x] [pipedrive](https://pipedrive.readme.io/docs/core-api-concepts-rate-limiting)
  - [x] https://github.com/fastify/fastify-rate-limit npm package
  - [x] https://github.com/apioo/fusio
 
WIP in

  - [ ] [tollbooth](https://github.com/didip/tollbooth/pull/96)

Support via configuration from:

  - [Azure API Gateway exposes functionalities to implement this](https://azure.microsoft.com/en-ca/updates/azure-api-management-update-january-2020/)
[IBM api gateway](https://www.ibm.com/support/knowledgecenter/en/SS9H2Y_7.7.0/com.ibm.dp.doc/apirequestrouting_apiratelimit.html)
  - [datadog](https://docs.datadoghq.com/api/v2/)
  - [ensembl genomic browser api](https://github.com/Ensembl/ensembl-rest)
  - [the hub controller](https://api.hubcontrols.com/)

Uses 429 and the triple like the following 

```
x-ratelimit-limit: 5000
x-ratelimit-remaining: 50
x-ratelimit-reset: 10  # delta seconds
```

Can be implemented? Yes

#### Google

Returns 429 or 403 depending on the API.

#### Yelp
Returns 429

```
RateLimit-DailyLimit: 5000
RateLimit-Remaining: 4999
RateLimit-ResetTime: 2018-03-28T00:00:00+00:00
```

Considerations:
- doesn't prefix headers with `Yelp-` see https://tools.ietf.org/html/rfc6648
- uses RFC3339 which is fine but different from Retry-After, nice thing uses another header name
- non clock-skew safe

Can be implemented with this spec? Yes, eg:

```
RateLimit-Limit: 5000
RateLimit-Policy:    5000; w=86400   # expliciting daily window in the optional comment part
RateLimit-Remaining: 4999
RateLimit-Reset: 36000                             # 10 hours before reset time
```

#### Amazon 

Amazon uses custom headers with `x-mws-quota-resetsOn` using the `IMF-fixdate` syntax.
The `time-window` is hourly. 

```
x-mws-quota-max: 3600
x-mws-quota-remaining: 10
x-mws-quota-resetsOn: Wed, 06 Mar 2013 19:07:58 GMT

```
Can be implemented with this spec? Yes, switching to `delta-seconds` eg:
```
RateLimit-Limit: 3600
RateLimit-Policy: 3600;w=3600
RateLimiit-Remaining: 10
RateLimit-Reset: 1000
```

#### Github

Uses 429 and the triple like the following 

```
x-ratelimit-limit: 5000
x-ratelimit-remaining: 50
x-ratelimit-reset: 1563525874  # unix timestamp
```

considerations: 
- non clock-skew safe
- different from retry-after 

Can be implemented with this spec? Yes, but should change the x-ratelimit-reset semantic

#### twitter, axway, oracle

- https://developer.twitter.com/en/docs/basics/rate-limiting.html
- [axway]( https://docs.axway.com/bundle/APIGateway_762_PolicyDevFilterReference_allOS_en_HTML5/page/Content/PolicyDevTopics/content_max_messages.htm)
- [oracle](https://docs.oracle.com/cd/E50612_01/doc.11122/user_guide/content/content_max_messages.html

Uses 429 and the triple like the following (same as github, but with different names)

```
x-rate-limit-limit: 5000
x-rate-limit-remaining: 50
x-rate-limit-reset: 1563525874  # unix timestamp
```

#### mulesoft

https://docs.mulesoft.com/api-manager/2.x/rate-limiting-and-throttling-sla-based-policies

Uses delta-seconds with milliseconds

```
x-ratelimit-limit: 5000
x-ratelimit-remaining: 50
x-ratelimit-reset: 12000  # milliseconds
```

## Other implementers

- [shipcloud](https://developers.shipcloud.io/concepts/)
- https://code-repo.d4science.org/D-Net/dnet-hadoop
-

**Comment by darrelmiller** [comment]
Based on many discussions in this working group, the decision was made to not maintain compatibility with the existing HTTP headers used in the wild.  Hopefully, there is enough additional value in the currently proposed draft  https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers for implementers to see value in migrating to the new headers once standardized.

**Comment by ioggstream** [comment]
Let's close this then :)
