### ISSUE TITLE
Performance concerns on returning fields on every response

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/ratelimit-headers#27]
## I expect

To define whether  those fields should be returned on every response.

## Note

This specification does not define whether the fields should be returned on every response or only when quota is going to expire.

About performance, we have to say that services interested in rate-limit are usually high-value services (Eg. e-pay, booking, billed services, ..) which have the business need of minimizing the costs of a failed transaction.

Implementers usually manage those fields via API Gateways which take care of a lot of headers. Moreover, those fields are conveyed in responses which usually have a `payload body` or `content`: this means the ratio b/w the field and data section of the response is significantly lower wrt eg. a GET request.  See for example this article about the [benefits of HPACK in request vs responses](https://blog.cloudflare.com/hpack-the-silent-killer-feature-of-http-2/#responseheaders)

cc: @darrelmiller

**Comment by unleashed** [comment]
I think you wanted to ping this other @darrelmiller.
