### ISSUE TITLE
terminology: "client application" -> "user agent"

### ISSUE THREAD

**Issue by reschke** [ietf-wg-httpapi/ratelimit-headers#3]

**Comment by ioggstream** [comment]
In other parts of the document we still use client as we are not sure whether to refer explicitly to a User Agent or not. Ideas welcome...

**Comment by reschke** [comment]
See RFC 7230 terminology definitions (<https://greenbytes.de/tech/webdav/rfc7230.html#rfc.section.2.1>, not changing in the new specs, FWIW).
