### ISSUE TITLE
Pre-Emptive Client Backoff

### ISSUE THREAD

**Issue by mfortini** [ietf-wg-httpapi/ratelimit-headers#36]
## Client should backoff nearing saturation

(Erik de Kok, Mimecast)

We used the Limit and Remain values in one of our client applications that was migrated from a legacy SOAP service to our REST based API in order to ensure we never get a 429 response (this is because the legacy code could not gracefully retry requests without major refactoring). 

When we get to 80% of quota (20% Remain) we start respecting the value in the Reset header. In section 7 you touched on a concept _‘A client SHOULD NOT exceed the "quota-units" expressed in "RateLimit-Remaining" before the "time-window" expressed in "RateLimit-Reset".’_  

> Would it be an idea to document that clients should be coded to pre-emptively back-off when nearing “saturation”?

We don't want to mandate a strict behavior on client, but we can surely add this sentence as an example behavior.

### Note

> Would one want to have to option to provide a saturation hint in the Limit definition ?

The current spec allows `Limit` comments, so you can already do it. The spec allows to address this use-case transparently, by artificially lowering the values provided in the fields.

**Comment by ioggstream** [comment]
We should probably integrate and remove [FAQ 8](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#section-appendix.b-1.8.1) since it's already in the spec.

**Comment by unleashed** [comment]
> Would one want to have to option to provide a saturation hint in the Limit definition ?

This is something I quickly commented on https://github.com/ietf-wg-httpapi/ratelimit-headers/pull/34#discussion_r589463844 but the alternative of dynamically modifying the values as the rate saturates is fairly reasonable, so those informational parameters might as well be part of an extension document.
