### ISSUE TITLE
Improve the description of Missing `Remaining` information.

### ISSUE THREAD

**Issue by mfortini** [ietf-wg-httpapi/ratelimit-headers#37]
https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#name-missing-remaining-informati

The example with just RateLimit-Limit and RateLimit-Reset  

In [3.1](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#name-ratelimit-limit) it seems this is a case where the RateLimit-Reset  value is not able to be used to determine how long one should wait, but is rather  just a Limit definition ? 

Why not then just use RateLimit-Limit: 10;w=1 and omit the other two headers ? 

Is this to cater for the inevitable 429 to provide a RateLimit-Reset value at that point ? 
If that is the case I question the value of using the two headers in “successful” responses.

**Comment by ioggstream** [comment]
This example is related to an implementation that uses the "old" ratelimit field set, that do not support `w`.
We should improve the description.
