### ISSUE TITLE
Section 8.1.4 and Appendix B.3.

### ISSUE THREAD

**Issue by mfortini** [ietf-wg-httpapi/ratelimit-headers#38]
You mention _` The "429 Too Many Requests" HTTP status code is just used as an example. `_. and _` No.  [RFC6585] defines the "429" status code and we use it just as an example of a throttled request, that could instead use even 403 or whatever status code. `_
I am curious why this isn’t specified as the expected HTTP status code when rate limited ? It is quite explicit and meaningful. Also see my related comment about RateLimit-Remaining: 0 below (#42)

https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#name-use-in-throttled-responses

https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#name-faq

(Erik de Kok, Mimecast)

**Comment by ioggstream** [comment]
We don't want to define a framework, but standardize the semantic of a set of headers already used in the wild in many ways.

I'll add a FAQ.
