### ISSUE TITLE
Relations with redirections 30x

### ISSUE THREAD

**Issue by mfortini** [ietf-wg-httpapi/ratelimit-headers#41]
## Question 

> Should the document state which HTTP status codes could expect rate limit headers ? 

No

> 5xx errors are for example unlikely to have them but also may not be precluded.

Correct 

> Would it be right for some 30x redirections to have them ? Is this too much detail ?

Probably we should warn that returning a `Remaining: 0` with 30x could refrain clients to make a request, but I won't be normative on that cc: @unleashed

**Comment by ioggstream** [comment]
See #44 

We need to provide guidance in redirection cases, probably.
