### ISSUE TITLE
Upper bound for RateLimit-Reset

### ISSUE THREAD

**Issue by ioggstream** [ietf-wg-httpapi/ratelimit-headers#84]
## I expect

The delta-seconds used for RateLimit-Reset to have an upper bound.

We could say that:

if the value is higher than x it could be processed as an UNIX Timestamp.

## Notes
Could 2 days be enough? (eg. 48*3600).

I don't expect issues if I don't respect a 2-day request-quota, though this choice is really arbitrary;

**Comment by unleashed** [comment]
What's the objective of doing this? Setting an absolute timestamp value as the reset assuming everyone is NTP sync'ed?

**Comment by ioggstream** [comment]
It's an old issue I did not port back to the new repo, and that should be discussed.

**Comment by ioggstream** [comment]
Retry-After does not have such considerations, so I think we can live without them.

**Comment by ioggstream** [comment]
Closed using prose in #99
