### ISSUE TITLE
Quota Units and Service Limits

### ISSUE THREAD

**Issue by mnot** [ietf-wg-httpapi/ratelimit-headers#92]
Section 2.2: 

> The service-limit is a non-negative Integer expressed in "quota-units".

Section 2.3:

> A "quota-policy" describes a quota policy in terms of [quota-units](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#service-limit) ([Section 2.2](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#service-limit)) and [time-window](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#time-window) ([Section 2.1](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#time-window)). Its value is an Item where the associated bare item is a [service-limit](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#service-limit) ([Section 2.2](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#service-limit)) and parameters are supported.[¶](https://ietf-wg-httpapi.github.io/ratelimit-headers/draft-ietf-httpapi-ratelimit-headers.html#section-2.3-1)

This appears to be a circular definition -- what's actually being defined here?

**Comment by mnot** [comment]
(noting that 2.2 doesn't actually define quota-units)

**Comment by ioggstream** [comment]
Quota unit is now defined as the measurement unit for service limits.

**Comment by mnot** [comment]
PTAL - I tried to rearrange to address this a bit more holistically.
